name: Tests

on: [push]

jobs:
  test:
    name: ${{ matrix.os }} / node@${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [8.10.0, 10, 12]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Run actions/setup-node@v1 with node@${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: npm install
        run: npm install
      - name: npm test
        run: npm test
